theme = "catppuccin_mocha_transparent"

[editor]
true-color = true
rulers = [100]
popup-border = "all"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-y = ["scroll_up"]
C-e = ["scroll_down" ]
C-x = ":q"
A-s = ":w!"
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"
A-L = ":vsplit"
A-J = ":hsplit"
A-F = ":sh zellij action new-pane -f -c -- nu -c \"yazi %{buffer_name}\""
A-C = ":sh zellij action new-pane -f -c -- nu -e \"cd (dirname %{buffer_name})\""

[keys.normal.space.space]
"l" = ":pipe ~/bin/hx-llm.py"

[keys.select.space.space]
"l" = ":pipe ~/bin/hx-llm.py"


[keys.select]
C-y = ["scroll_up"]
C-e = ["scroll_down"]
