#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries
# after BTRFS snapshots.
menuentry "Windows 10" {
	set root=(hd0,gpt2)
	chainloader /efi/Microsoft/Boot/bootmgfw.efi
}
